[package]
name = "day_11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file_utils = { path = "../file_utils" }
regex = "1"
lazy_static = "1.4.0"
